# Generated by Django 2.0.13 on 2019-04-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logger', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggerserverstatus',
            name='logger_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_status', to='logger.LoggerServer'),
        ),
        migrations.AddField(
            model_name='clientserver',
            name='logger_servers',
            field=models.ManyToManyField(related_name='client_servers', through='dashboard.LoggerServerStatus', to='logger.LoggerServer'),
        ),
    ]
