# Generated by Django 2.0.13 on 2019-05-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_apachehttpdgenerator'),
        ('dashboard', '0002_auto_20190408_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('client_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generator_status', to='dashboard.ClientServer')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_status', to='generator.Generator')),
            ],
        ),
        migrations.AddField(
            model_name='clientserver',
            name='generators',
            field=models.ManyToManyField(related_name='client_servers', through='dashboard.GeneratorStatus', to='generator.Generator'),
        ),
    ]
