# Generated by Django 2.0.13 on 2019-05-06 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190506_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientserver',
            name='recurrence',
            field=models.DurationField(default=datetime.timedelta(0, 5)),
        ),
    ]
