# Generated by Django 2.0.13 on 2019-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_clientserver_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientserver',
            name='last_run',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
