# Generated by Django 2.0.13 on 2019-05-07 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190506_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientserver',
            name='last_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
