# Generated by Django 2.0.13 on 2019-04-08 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogLoggerServer',
            fields=[
                ('loggerserver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.LoggerServer')),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.IntegerField(choices=[(0, 'TCP'), (1, 'UDP')], default=0)),
                ('facility', models.IntegerField(choices=[(0, 'kern'), (1, 'user'), (2, 'mail'), (3, 'daemon'), (4, 'auth'), (5, 'syslog'), (6, 'lpr'), (7, 'news'), (8, 'uucp'), (9, 'cron'), (10, 'authpriv'), (11, 'ftp'), (12, 'ntp'), (13, 'security'), (14, 'console'), (15, 'solaris-cron'), (16, 'local0'), (17, 'local1'), (18, 'local2'), (19, 'local3'), (20, 'local4'), (21, 'local5'), (22, 'local6'), (23, 'local7')], default=16)),
                ('default_log_level', models.IntegerField(choices=[(0, 'emerg'), (1, 'alert'), (2, 'crit'), (3, 'err'), (4, 'warning'), (5, 'notice'), (6, 'info'), (7, 'debug')], default=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('logger.loggerserver',),
        ),
    ]
