# Generated by Django 2.0.13 on 2019-05-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_syslogloggerserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLoggerServer',
            fields=[
                ('loggerserver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.LoggerServer')),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('protocol', models.IntegerField(choices=[(0, 'TCP'), (1, 'UDP')], default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('logger.loggerserver',),
        ),
        migrations.RemoveField(
            model_name='syslogloggerserver',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='syslogloggerserver',
            name='loggerserver_ptr',
        ),
        migrations.RemoveField(
            model_name='syslogloggerserver',
            name='port',
        ),
        migrations.RemoveField(
            model_name='syslogloggerserver',
            name='protocol',
        ),
        migrations.AddField(
            model_name='syslogloggerserver',
            name='rawloggerserver_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logger.RawLoggerServer'),
            preserve_default=False,
        ),
    ]
