# Generated by Django 2.0.13 on 2019-05-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regexgenerator',
            name='regex',
            field=models.CharField(max_length=10000),
        ),
    ]
