# Generated by Django 2.0.13 on 2019-05-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_apachehttpdgenerator_random_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apachehttpdgenerator',
            name='custom_url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='apachehttpdgenerator',
            name='only_get_post_verb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apachehttpdgenerator',
            name='only_http_11',
            field=models.BooleanField(default=True),
        ),
    ]
