from django.urls import path

from . import views

urlpatterns = [
    path(
        'regex/create',
        views.RegexGeneatorCreateView.as_view(),
        name='generator-regex-create'),
    path(
        'regex/<int:pk>',
        views.RegexGeneratorDetailView.as_view(),
        name='generator-regex-detail'),
    path(
        'regex/edit/<int:pk>',
        views.RegexGeneratorUpdateView.as_view(),
        name='generator-regex-edit'),
    path(
        'grok/create',
        views.GrokGeneatorCreateView.as_view(),
        name='generator-grok-create'),
    path(
        'grok/<int:pk>',
        views.GrokGeneratorDetailView.as_view(),
        name='generator-grok-detail'),
    path(
        'grok/edit/<int:pk>',
        views.GrokGeneratorUpdateView.as_view(),
        name='generator-grok-edit'),
    path(
        'httpd/create',
        views.ApacheHttpdGeneatorCreateView.as_view(),
        name='generator-httpd-create'),
    path(
        'httpd/<int:pk>',
        views.ApacheHttpdGeneratorDetailView.as_view(),
        name='generator-httpd-detail'),
    path(
        'httpd/edit/<int:pk>',
        views.ApacheHttpdGeneratorUpdateView.as_view(),
        name='generator-httpd-edit'),
    path(
        'vsftpd/create',
        views.VsftpdGeneatorCreateView.as_view(),
        name='generator-vsftpd-create'),
    path(
        'vsftpd/<int:pk>',
        views.VsftpdGeneratorDetailView.as_view(),
        name='generator-vsftpd-detail'),
    path(
        'vsftpd/edit/<int:pk>',
        views.VsftpdGeneratorUpdateView.as_view(),
        name='generator-vsftpd-edit'),
    path(
        'sshd/create',
        views.SshdGeneatorCreateView.as_view(),
        name='generator-sshd-create'),
    path(
        'sshd/<int:pk>',
        views.SshdGeneratorDetailView.as_view(),
        name='generator-sshd-detail'),
    path(
        'sshd/edit/<int:pk>',
        views.SshdGeneratorUpdateView.as_view(),
        name='generator-sshd-edit'),
    path(
        'delete/<int:pk>',
        views.GeneratorDeleteView.as_view(),
        name='generator-delete'),
    path(
        'generate/<int:pk>',
        views.GeneratorGenerateView.as_view(),
        name='generator-generate'),
    path('', views.GeneratorListView.as_view(), name='generator-list'),
]
